/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author orlandocamacho
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpStudentData = new javax.swing.JPanel();
        jpCourses = new javax.swing.JPanel();
        jpStatus = new javax.swing.JPanel();
        jlStatus = new javax.swing.JLabel();
        jpHeader = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jpTitles = new javax.swing.JPanel();
        jlStudentSectionTitle = new javax.swing.JLabel();
        jlCoursesSectionTitle = new javax.swing.JLabel();
        jlMainTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITSON");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpStudentData.setBackground(new java.awt.Color(255, 255, 255));
        jpStudentData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jpStudentData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 350));

        jpCourses.setBackground(new java.awt.Color(255, 255, 255));
        jpCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jpCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 450, 350));

        jpStatus.setBackground(new java.awt.Color(255, 255, 255));
        jpStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlStatus.setText("Enviando datos del alumno... - Esperando respuesta del servidor... - Recibiendo datos de los cursos...");
        jpStatus.add(jlStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 680, 20));

        getContentPane().add(jpStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 700, 20));

        jpHeader.setBackground(new java.awt.Color(15, 109, 181));
        jpHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jpHeader.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jpTitles.setBackground(new java.awt.Color(13, 85, 136));
        jpTitles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlStudentSectionTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlStudentSectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlStudentSectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStudentSectionTitle.setText("Datos del alumno");
        jpTitles.add(jlStudentSectionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 0, 210, 30));

        jlCoursesSectionTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlCoursesSectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlCoursesSectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCoursesSectionTitle.setText("Cursos ofertados disponibles para el alumno");
        jpTitles.add(jlCoursesSectionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 410, 30));

        jpHeader.add(jpTitles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 30));

        jlMainTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlMainTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlMainTitle.setText("Oferta educativa de cursos ISW");
        jpHeader.add(jlMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 280, 30));

        getContentPane().add(jpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCoursesSectionTitle;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlMainTitle;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlStudentSectionTitle;
    private javax.swing.JPanel jpCourses;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JPanel jpStatus;
    private javax.swing.JPanel jpStudentData;
    private javax.swing.JPanel jpTitles;
    // End of variables declaration//GEN-END:variables
}
